version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
  build:
    commands:
      - cd search-photos
      - npm ci

artifacts:
  files:
    - '**/*'
  base-directory: search-photos